// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQwlVToTZ60-W4YrBHvQtTmpG48ciAIc',
    appId: '1:303670165135:web:69cb573749138826337afa',
    messagingSenderId: '303670165135',
    projectId: 'food1-8b916',
    authDomain: 'food1-8b916.firebaseapp.com',
    storageBucket: 'food1-8b916.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-gkRcxbr1oIlE4s0egnZxCsWMldes_g',
    appId: '1:303670165135:android:fad0881903fa62b0337afa',
    messagingSenderId: '303670165135',
    projectId: 'food1-8b916',
    storageBucket: 'food1-8b916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChmyRexB_1lMmy6uooreR2xu6r1wWWYY',
    appId: '1:303670165135:ios:2db57c6d8bc62803337afa',
    messagingSenderId: '303670165135',
    projectId: 'food1-8b916',
    storageBucket: 'food1-8b916.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCChmyRexB_1lMmy6uooreR2xu6r1wWWYY',
    appId: '1:303670165135:ios:2db57c6d8bc62803337afa',
    messagingSenderId: '303670165135',
    projectId: 'food1-8b916',
    storageBucket: 'food1-8b916.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAQwlVToTZ60-W4YrBHvQtTmpG48ciAIc',
    appId: '1:303670165135:web:734496128ea71415337afa',
    messagingSenderId: '303670165135',
    projectId: 'food1-8b916',
    authDomain: 'food1-8b916.firebaseapp.com',
    storageBucket: 'food1-8b916.firebasestorage.app',
  );

}